baseURL = "https://github.eugenego.club/"
languageCode = "en-us"
title = "Eugene Go Club"
theme = "PaperMod"

[params]
ShowBreadCrumbs = true
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true

[params.homeInfoParams]
Title = "Hello"
Content = "Welcome to the club. Here you'll find a lot of cool information about go."

[params.cover]
linkFullImages = true

[[menu.main]]
identifier = "Meetup.com"
name = "Meetup.com"
url = "https://www.meetup.com/eugene-go-players/"
weight = 10

[[menu.main]]
identifier = "Patterns"
name = "Patterns"
url = "/patterns/"
weight = 20

[[menu.main]]
identifier = "Joseki"
name = "Joseki"
url = "/joseki/"
weight = 30

[[menu.main]]
identifier = "Games"
name = "Games"
url = "/games/"
weight = 40

[[menu.main]]
identifier = "Proverbs"
name = "Proverbs"
url = "/proverbs/"
weight = 50

[[menu.main]]
identifier = "FAQ"
name = "FAQ"
url = "/faq/"
weight = 60
