baseURL: "https://github.eugenego.club/"
languageCode: en-us
title: Eugene Go Club
theme: PaperMod

params:
  assets:
    disableFingerprinting: true

  homeInfoParams:
    Title: "Wednesdays 5-9pm"
    Content: Here you'll find an archive of the weekly games played @ 5th Street Market Alley.

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  # ShowShareButtons: true

  ShowPostNavLinks: true

menu:
  main:
    - identifier: Archives
      name: Archives
      url: /archives/
      weight: 10
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: Meetup.com
      name: Meetup.com
      url: /meetup/
      weight: 30
    # - identifier: Search
    #   name: Search
    #   url: /search/
    #   weight: 10
    # - identifier: Proverbs
    #   name: Proverbs
    #   url: /proverbs/
    #   weight: 50
    # - identifier: FAQ
    #   name: FAQ
    #   url: /faq/
    #   weight: 60
