baseURL: "https://github.eugenego.club/"
languageCode: en-us
title: Eugene Go Club
theme: PaperMod

params:
  assets:
    disableFingerprinting: true

  homeInfoParams:
    Title: "Hello"
    Content: Welcome to the club. Here you'll find a lot of cool information about go.

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true

menu:
  main:
    - identifier: Archives
      name: Archives
      url: /archives/
      weight: 10
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: Meetup.com
      name: Meetup.com
      url: https://www.meetup.com/eugene-go-players/
      weight: 30
    # - identifier: Search
    #   name: Search
    #   url: /search/
    #   weight: 10
    # - identifier: Proverbs
    #   name: Proverbs
    #   url: /proverbs/
    #   weight: 50
    # - identifier: FAQ
    #   name: FAQ
    #   url: /faq/
    #   weight: 60
